onboarding = false

[theme]
name = "dracula"
auto_switch = false

[ui]
status_indicators = "symbols"

[keys]
resize_pane_left = "prefix+left"
resize_pane_down = "prefix+down"
resize_pane_up = "prefix+up"
resize_pane_right = "prefix+right"

focus_agent = "prefix+a+1..9"

[[keys.command]]
key = "prefix+shift+g"
type = "popup"
command = "lazygit"
description = "run lazygit"
width = "90%"
height = "80%"

