hide_window_decorations titlebar-only
window_padding_width 0

background_image ~/.config/kitty/bg.jpg
background_tint 0.97
background_image_layout cscaled
background_image_linear yes

copy_on_select clipboard
allow_remote_control yes

mouse_hide_wait 0
tab_bar_style hidden

# BEGIN_KITTY_FONTS
font_family      family="FantasqueSansM Nerd Font Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS


